kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-s-1-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
