apiVersion: apps/v1beta1
kind: StatefulSet 
metadata:
  namespace: default 
  name: redis-slave-1
spec:
  serviceName: "redis-slave"
  podManagementPolicy: Parallel
  replicas: 1
  template:
    metadata:
      labels:
        component: redis-slave
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis-slave-1
          image: 10.254.0.50:5000/redis:3.2 
          imagePullPolicy: Always
          command: ["/workspace/entrypoint.active-backup.sh"]
          env:
            - name: DSCV
              value: redis-master
            - name: MASTER_IP 
              value: 10.254.63.79 
            - name: ROLE
              value: SLAVE 
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: redis-s-1-claim
              mountPath: /data
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: redis-s-1-claim
          persistentVolumeClaim:
            claimName: redis-s-1-pv
